name: Wallapop Lavadora relojes Monitor

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

env:
  # Forzamos Node 24 para evitar avisos de obsolescencia en 2026
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repositorio
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm'
          # Esta ruta debe ser exacta. Si el archivo está en la raíz, quita "buscador-mercado/"
          cache-dependency-path: './package-lock.json'

      - name: Instalar dependencias
        # Usamos 'working-directory' para que npm sepa dónde entrar
        working-directory: ./
        run: npm install

      - name: Ejecutar búsqueda de Lavadora relojes
        working-directory: ./
        run: node index.js
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}

      - name: Guardar historial de búsqueda
        working-directory: ./
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          # Añadimos el archivo específico de la carpeta
          git add last_ids.json || exit 0
          git commit -m "Update history: [skip ci]" || exit 0
          git push
