name: Wallapop Lavadora relojes Monitor

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

env:
  # Evita avisos de versiones antiguas de Node en el log
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repositorio
        uses: actions/checkout@v4

      # Este paso es para confirmar dónde están los archivos realmente
      - name: Listar archivos (Debug)
        run: ls -R

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          # Eliminamos el caché temporalmente para evitar errores de ruta
          # Si esto funciona, luego podemos volver a activarlo

      - name: Instalar dependencias
        # Ejecutamos directamente en la raíz
        run: npm install

      - name: Ejecutar búsqueda
        run: node index.js
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}

      - name: Guardar historial de búsqueda
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add last_ids.json || exit 0
          git commit -m "Update history: [skip ci]" || exit 0
          git push